### ISSUE TITLE
How many hours do you have when running OpenBSD under X201?

### ISSUE THREAD

**Issue by diogin** [zacbrown/configs#1]
Hello, just googled "openbsd x201" and find your blog post on it.
I'm running OpenBSD 5.7 amd64 under ThinkPad X201 too, but I got a terrible battery life.
CPU fan is always running in its max speed, blowing hot air.
The temperature is around 59C.
I tried to tune sysctl hw.cpuspeed and hw.setperf to a lower state but the result remains.
So could you share your experience on power saving?
Thanks very much!

**Comment by zacbrown** [comment]
I've not got any experience running 5.7 on the x201. My experience was only on 5.6.
